<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kelas</name>
   <tag></tag>
   <elementGuidId>d47fb5b2-f603-4cfb-86ce-f5877f71c948</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[text()='Kelas']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e28317d6-8522-4501-bef8-820624101177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/kelas</value>
      <webElementGuid>7ae93d67-d692-4ce0-a1cc-17ac8cd1290b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white hover:text-amber-500 flex items-center p-2 pl-11 w-full rounded-lg transition duration-75 group text-sm</value>
      <webElementGuid>e6866859-2020-4203-990d-fc5f9f900c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kelas</value>
      <webElementGuid>abd656f8-02ce-4097-bc8a-59b6568bec9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left-navigation&quot;)/div[@class=&quot;px-4 h-full scroll mt-8 svelte-og1l5i&quot;]/div[2]/ul[@class=&quot;space-y-2 tracking-wide mt-8 transition duration-500&quot;]/li[@class=&quot;whitespace-nowrap&quot;]/ul[@class=&quot;py-2 space-y-2 dropdown-elm&quot;]/li[1]/a[@class=&quot;text-white hover:text-amber-500 flex items-center p-2 pl-11 w-full rounded-lg transition duration-75 group text-sm&quot;]</value>
      <webElementGuid>52adcbd5-df6d-4b04-ba9c-0361ebd54397</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='left-navigation']/div/div[2]/ul/li[4]/ul/li/a</value>
      <webElementGuid>1fa9b507-a170-4ea0-a538-3de984d05b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kelas')]</value>
      <webElementGuid>33a3e6ed-e187-456e-abe9-14e038d090d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/kelas')]</value>
      <webElementGuid>5195a609-49f6-4473-b355-11e5f990ec9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li/a</value>
      <webElementGuid>f1a63497-ccc5-41ca-b5ab-066c35f27701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/kelas' and (text() = 'Kelas' or . = 'Kelas')]</value>
      <webElementGuid>12236dee-844c-4f75-af52-65744f2927b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
