<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kelas</name>
   <tag></tag>
   <elementGuidId>5d85ea87-ab83-4409-81ba-f8e813228b82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[text()='Kelas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>15a86286-d02c-442c-9db7-79b5a24e7fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/kelas</value>
      <webElementGuid>b218f532-d764-453a-ad3f-ccd2b30138f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white hover:text-amber-500 flex items-center p-2 pl-11 w-full rounded-lg transition duration-75 group text-sm</value>
      <webElementGuid>83dbfbad-7b0d-4519-9f02-dd295fb0a671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kelas</value>
      <webElementGuid>c7902322-5855-49c1-a53c-c0168abfdd77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left-navigation&quot;)/div[@class=&quot;px-4 h-full scroll mt-8 svelte-og1l5i&quot;]/div[2]/ul[@class=&quot;space-y-2 tracking-wide mt-8 transition duration-500&quot;]/li[@class=&quot;whitespace-nowrap&quot;]/ul[@class=&quot;py-2 space-y-2 dropdown-elm&quot;]/li[1]/a[@class=&quot;text-white hover:text-amber-500 flex items-center p-2 pl-11 w-full rounded-lg transition duration-75 group text-sm&quot;]</value>
      <webElementGuid>5a72e484-f822-4567-884f-9f6308e0f43b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='left-navigation']/div/div[2]/ul/li[4]/ul/li/a</value>
      <webElementGuid>5828a6b8-6e59-42f8-8bba-46cadbc15ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kelas')]</value>
      <webElementGuid>63439f06-5fc7-4d21-87a0-bdb851aa76c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/kelas')]</value>
      <webElementGuid>9f99c3ef-6fec-4a3c-8e29-92d4f5feb46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li/a</value>
      <webElementGuid>7607b956-562d-45eb-a3bd-bc07ba6b5d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/kelas' and (text() = 'Kelas' or . = 'Kelas')]</value>
      <webElementGuid>9b217e5e-edac-4cc4-b6c6-af31457f3dae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
