<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Berikutnya</name>
   <tag></tag>
   <elementGuidId>34c7bfb4-27e9-4df6-bb36-0aab84239bde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>795a956a-c3ad-4bf0-b512-b38d80aa017f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>18a20fda-44ad-4913-97d2-54e26a490ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-5 w-full h-[50px] text-white font-normal bg-emerald-600 cursor-pointer rounded-md</value>
      <webElementGuid>997419fa-1031-419e-a35b-8db7d01a9a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berikutnya</value>
      <webElementGuid>435219c1-92e9-4b7c-bd6d-2e8c8f6048ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[@class=&quot;w-screen h-screen flex justify-center items-center bg-[#f7f1e4]&quot;]/div[1]/div[@class=&quot;p-4 sm:p-0&quot;]/div[@class=&quot;flex flex-col w-full p-6 sm:p-10 rounded-md bg-white mt-4&quot;]/div[@class=&quot;content&quot;]/button[@class=&quot;mt-5 w-full h-[50px] text-white font-normal bg-emerald-600 cursor-pointer rounded-md&quot;]</value>
      <webElementGuid>45e65a99-f3d9-4274-9a10-d3f469b5ce77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>03a33e92-432b-484c-97ed-aba01c5f9f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>8b0ddf51-8778-4fca-a17e-6b653ac89536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Berikutnya' or . = 'Berikutnya')]</value>
      <webElementGuid>c35f35be-f2b0-4e7d-a256-12fa8c7e6148</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
