<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>c4316d42-3220-411b-965e-b6326a452aa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.text-white.rounded.py-2.px-16.border.bg-teal-600.text-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(text(), 'Simpan')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>23ad7820-4291-4c7d-bb15-7ff43fb70039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white rounded py-2 px-16 border bg-teal-600 text-sm</value>
      <webElementGuid>ed808a25-4cd1-4a0a-907c-4f4a2714d786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>899dc953-bbb4-4f54-b6fd-b36fa1b62124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[2]/div[@class=&quot;flex&quot;]/div[@class=&quot;pb-6 w-full bg-[#e8efee] min-h-screen lg:pl-[246px] main-container-transition-open svelte-og1l5i&quot;]/div[@class=&quot;px-2 pt-2 w-full mx-auto h-auto&quot;]/div[@class=&quot;p-4 bg-white rounded shadow-[0px_1px_3px_0px_rgb(54,74,99,0.05)] space-y-4&quot;]/div[3]/div[@class=&quot;flex flex-col w-full items-center justify-center mt-3&quot;]/button[@class=&quot;text-white rounded py-2 px-16 border bg-teal-600 text-sm&quot;]</value>
      <webElementGuid>095eb090-b4e3-48bc-a5f7-a756ab4cb2de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button</value>
      <webElementGuid>8c624e53-fa8b-4896-b577-f1fb0e45ae5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>200e121f-5b46-419e-b48a-382ece9e44e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
