<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Kelas</name>
   <tag></tag>
   <elementGuidId>735902c3-45ca-4c56-9e74-b1b5ed71ae40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.bg-transparent.p-1.px-2.appearance-none.outline-none.h-full.w-full.text-gray-800</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;flex mt-5&quot;]//div[1]//div//div//div[1]//div//div//div//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae9f4a8a-0ad3-446b-bfbf-7296966a500a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-transparent p-1 px-2 appearance-none outline-none h-full w-full text-gray-800</value>
      <webElementGuid>55cd85a5-bf7e-4a6c-b857-3adc81d1d25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[2]/div[@class=&quot;flex&quot;]/div[@class=&quot;pb-6 w-full bg-[#e8efee] min-h-screen lg:pl-[246px] main-container-transition-open svelte-og1l5i&quot;]/div[@class=&quot;px-2 pt-2 w-full mx-auto h-auto&quot;]/div[@class=&quot;p-4 bg-white rounded shadow-[0px_1px_3px_0px_rgb(54,74,99,0.05)] space-y-4&quot;]/div[3]/div[@class=&quot;flex mt-5&quot;]/div[@class=&quot;w-full md:w-1/2 flex flex-col items-center h-64 border border-gray-100 p-5&quot;]/div[@class=&quot;w-full px-4&quot;]/div[@class=&quot;flex flex-col items-center relative&quot;]/div[@class=&quot;w-full svelte-1l8159u&quot;]/div[@class=&quot;my-2 p-1 flex border border-gray-200 bg-white rounded svelte-1l8159u&quot;]/div[@class=&quot;flex flex-auto flex-wrap&quot;]/div[@class=&quot;flex-1&quot;]/input[@class=&quot;bg-transparent p-1 px-2 appearance-none outline-none h-full w-full text-gray-800&quot;]</value>
      <webElementGuid>7ff2b934-f1f3-4bb3-a77d-017ddc6160bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>52ebf5e9-f390-41e0-9011-8ec231053f39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
