<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox</name>
   <tag></tag>
   <elementGuidId>26b61086-3dc2-4ea2-aa84-068480dc740e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='1']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc2cbbd9-82ad-405c-844e-5df0bdb09583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>da992cab-5dff-48fe-964b-0c8341876bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>529d7c12-761f-4c8b-8397-beb6659275d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>77af6e62-0772-4d40-8277-56d72155e7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-check focus:opacity-100 checkbox absolute cursor-pointer w-full h-full appearance-none border-2 border-gray-500 bg-white checked:bg-transparent checked:border-0 svelte-181mww0</value>
      <webElementGuid>ec519eb0-ce8c-4f84-bb5c-db9768b44cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[2]/div[@class=&quot;flex&quot;]/div[@class=&quot;pb-6 w-full bg-[#e8efee] min-h-screen lg:pl-[246px] main-container-transition-open svelte-og1l5i&quot;]/div[@class=&quot;px-2 pt-2 w-full mx-auto&quot;]/div[@class=&quot;p-4 bg-white rounded shadow-[0px_1px_3px_0px_rgb(54,74,99,0.05)] space-y-4&quot;]/div[3]/div[@class=&quot;mt-4 overflow-x-auto&quot;]/table[@class=&quot;w-full whitespace-nowrap&quot;]/tbody[1]/tr[@class=&quot;even:bg-gray-100 h-[60px]&quot;]/td[1]/div[@class=&quot;ml-5&quot;]/div[@class=&quot;bg-gray-200 rounded-sm w-5 h-5 flex flex-shrink-0 justify-center items-center relative&quot;]/input[@class=&quot;input-check focus:opacity-100 checkbox absolute cursor-pointer w-full h-full appearance-none border-2 border-gray-500 bg-white checked:bg-transparent checked:border-0 svelte-181mww0&quot;]</value>
      <webElementGuid>2bd3fa80-a27a-4d62-80a7-a8a3bb47fd2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='4']</value>
      <webElementGuid>7ca13e30-6677-40d9-9a8b-0b28b4292328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/input</value>
      <webElementGuid>b6101416-76d5-43d5-909d-2cc9740f24d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'checkbox' and @type = 'checkbox']</value>
      <webElementGuid>c3903a00-cac6-4316-9599-ecda9d873778</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
