<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_input-check focusopacity-100 checkbox_dc82a2</name>
   <tag></tag>
   <elementGuidId>b12b0f67-43b0-46fa-a1cf-68dbeb3f553d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='44']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>930344f3-3922-467b-8b60-81bbe92afbcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cca19f1d-3e52-4b24-9e83-f8b7d1543990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>65ad28ee-1726-444e-bd5e-8d0bd335c449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>53</value>
      <webElementGuid>d3a53443-051d-4750-8244-2144c8fa504e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-check focus:opacity-100 checkbox absolute cursor-pointer w-full h-full appearance-none border-2 border-gray-500 bg-white checked:bg-transparent checked:border-0 svelte-egpy0w</value>
      <webElementGuid>af46071b-dbe3-4c36-ac1b-df9d35a3e33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[2]/div[@class=&quot;flex&quot;]/div[@class=&quot;pb-6 w-full bg-[#e8efee] min-h-screen lg:pl-[246px] main-container-transition-open svelte-og1l5i&quot;]/div[@class=&quot;px-2 pt-2 w-full mx-auto&quot;]/div[@class=&quot;w-full bg-white rounded shadow-[0px_1px_3px_0px_rgb(54,74,99,0.05)] p-4 space-y-4&quot;]/div[3]/div[@class=&quot;w-full overflow-x-auto&quot;]/table[@class=&quot;responsive-table&quot;]/tbody[@class=&quot;text-sm&quot;]/tr[6]/td[@class=&quot;pl-5&quot;]/div[1]/div[@class=&quot;bg-gray-200 rounded-sm w-5 h-5 flex flex-shrink-0 justify-center items-center relative&quot;]/input[@class=&quot;input-check focus:opacity-100 checkbox absolute cursor-pointer w-full h-full appearance-none border-2 border-gray-500 bg-white checked:bg-transparent checked:border-0 svelte-egpy0w&quot;]</value>
      <webElementGuid>07b98536-4924-4520-a26d-4132a58250d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='53']</value>
      <webElementGuid>f025ff17-52c0-4478-bc66-8352e2380996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/div/div/input</value>
      <webElementGuid>79a8640b-8520-4cbc-a45f-b997296c3a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'checkbox' and @type = 'checkbox']</value>
      <webElementGuid>5cb8768f-a7d5-4d3a-b371-7a08d42fed44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
