<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kelas</name>
   <tag></tag>
   <elementGuidId>a5fa827b-8185-4637-8ccf-7b53fe4e67c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[text()='Kelas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>262dcd50-e943-4790-ad42-14ed0f665eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/kelas</value>
      <webElementGuid>3f8e71eb-1735-4f51-ba35-51abdf43bade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white hover:text-amber-500 flex items-center p-2 pl-11 w-full rounded-lg transition duration-75 group text-sm</value>
      <webElementGuid>02a792bb-7c0d-4576-ad03-0b3c5b2923f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kelas</value>
      <webElementGuid>52d39866-6b29-4bbd-9157-bcb8b7934f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left-navigation&quot;)/div[@class=&quot;px-4 h-full scroll mt-8 svelte-og1l5i&quot;]/div[2]/ul[@class=&quot;space-y-2 tracking-wide mt-8 transition duration-500&quot;]/li[@class=&quot;whitespace-nowrap&quot;]/ul[@class=&quot;py-2 space-y-2 dropdown-elm&quot;]/li[1]/a[@class=&quot;text-white hover:text-amber-500 flex items-center p-2 pl-11 w-full rounded-lg transition duration-75 group text-sm&quot;]</value>
      <webElementGuid>022b3403-bedc-4b00-811b-3aa97aa0cf8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='left-navigation']/div/div[2]/ul/li[4]/ul/li/a</value>
      <webElementGuid>6956a21b-5f79-4bec-bcd3-c84ab61befa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kelas')]</value>
      <webElementGuid>5e2a1886-e821-4ba5-b58b-38887905b88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/kelas')]</value>
      <webElementGuid>6cfbde7d-2e0e-4ec4-a205-8c38783b3ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li/a</value>
      <webElementGuid>1e4141ea-f613-454c-b79b-d1d9be5307d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/kelas' and (text() = 'Kelas' or . = 'Kelas')]</value>
      <webElementGuid>e32fd300-782f-496e-a897-abbb4bae359c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
