<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>editWali</name>
   <tag></tag>
   <elementGuidId>1c564fab-86ec-4754-ad14-280d7741c2b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;sm:flex sm:flex-row flex flex-col w-full sm:w-96 gap-2 md:py-6&quot;]//div[2]//div//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>f6445028-a22b-457e-95d6-d6ab21fd5ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>c8fc3f79-c9c7-492f-94ab-cf2f26be6d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>15e4c515-85b4-46cc-aac7-c5cebe613e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>6802dcef-48b0-4541-be54-cff6dc3655dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>bb1364e5-a60e-45ea-bdf5-880508f8d116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>fa8a7c36-fbd8-4c66-a534-6c0a578c131c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>1af17182-38cc-4965-a16f-07c19e4e6e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>64a09655-536a-43be-8712-94eca4d5837b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>bcfcf9a7-c479-4d8f-b212-d99044173fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>3d62c0d3-7920-4e1c-8792-18ae7dbf2ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feather feather-chevron-up w-4 h-4</value>
      <webElementGuid>ac9f7e6c-0d42-4702-9b4e-711c68a512da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[2]/div[@class=&quot;flex&quot;]/div[@class=&quot;pb-6 w-full bg-[#e8efee] min-h-screen lg:pl-[246px] main-container-transition-open svelte-og1l5i&quot;]/div[@class=&quot;px-2 pt-2 w-full mx-auto h-auto&quot;]/div[@class=&quot;p-4 bg-white rounded shadow-[0px_1px_3px_0px_rgb(54,74,99,0.05)] space-y-4&quot;]/div[3]/div[@class=&quot;flex mt-5&quot;]/div[@class=&quot;w-full md:w-1/2 flex flex-col items-center h-64 border border-gray-100 p-5&quot;]/div[@class=&quot;w-full px-4&quot;]/ul[1]/li[2]/div[@class=&quot;w-full&quot;]/div[@class=&quot;flex flex-col items-center relative&quot;]/div[@class=&quot;w-full svelte-1l8159u&quot;]/div[@class=&quot;my-2 p-1 flex border border-gray-200 bg-white rounded svelte-1l8159u&quot;]/button[@class=&quot;text-gray-300 w-8 py-1 pl-2 pr-1 border-l flex items-center border-gray-200 svelte-1l8159u&quot;]/button[@class=&quot;cursor-pointer w-6 h-6 text-gray-600 outline-none focus:outline-none&quot;]/svg[@class=&quot;feather feather-chevron-up w-4 h-4&quot;]</value>
      <webElementGuid>805e1594-5d9d-423b-9d35-399a013890d5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
