<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_input-check focusopacity-100 checkbox_3d5255</name>
   <tag></tag>
   <elementGuidId>f4a86a27-e96a-4bb5-844e-54f182d0e8d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='60']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7245b460-81b8-4e36-8f02-ca0efd1ea2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1f22bca6-176f-4636-9c12-5f51164bc3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>79541de7-10ae-4c84-a855-49d3940daa75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>f517df61-9294-49fb-b239-f35f1697fba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-check focus:opacity-100 checkbox absolute cursor-pointer w-full h-full appearance-none border-2 border-gray-500 bg-white checked:bg-transparent checked:border-0 svelte-181mww0</value>
      <webElementGuid>b507ba10-ef1a-4fff-add6-bc75e1877e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[2]/div[@class=&quot;flex&quot;]/div[@class=&quot;pb-6 w-full bg-[#e8efee] min-h-screen lg:pl-[246px] main-container-transition-open svelte-og1l5i&quot;]/div[@class=&quot;px-2 pt-2 w-full mx-auto&quot;]/div[@class=&quot;p-4 bg-white rounded shadow-[0px_1px_3px_0px_rgb(54,74,99,0.05)] space-y-4&quot;]/div[3]/div[@class=&quot;mt-4 overflow-x-auto&quot;]/table[@class=&quot;w-full whitespace-nowrap&quot;]/tbody[1]/tr[@class=&quot;even:bg-gray-100 h-[60px]&quot;]/td[1]/div[@class=&quot;ml-5&quot;]/div[@class=&quot;bg-gray-200 rounded-sm w-5 h-5 flex flex-shrink-0 justify-center items-center relative&quot;]/input[@class=&quot;input-check focus:opacity-100 checkbox absolute cursor-pointer w-full h-full appearance-none border-2 border-gray-500 bg-white checked:bg-transparent checked:border-0 svelte-181mww0&quot;]</value>
      <webElementGuid>16390440-c988-44f2-8fa6-4a7561961953</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='60']</value>
      <webElementGuid>e5a4e02a-49e8-46e7-a110-50411d8411d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/input</value>
      <webElementGuid>3a503fa1-ac91-42b0-b7b2-29d98b103b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'checkbox' and @type = 'checkbox']</value>
      <webElementGuid>584b94f6-6d3c-4364-8d6c-10f4afdf4701</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
