<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_input-check focusopacity-100 checkbox_dc82a2</name>
   <tag></tag>
   <elementGuidId>fe5ddf47-ca80-4c38-b8d9-9aa30e0f13d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='60']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af4b6a78-de11-48e9-b0be-24b1ae7a2292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fcc0ade1-c282-43f0-a271-587154b3bb07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a28c154a-78cf-4e04-9753-a0d83440d3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>1b2dc0c7-5db5-4b98-9db3-75ad4f205537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-check focus:opacity-100 checkbox absolute cursor-pointer w-full h-full appearance-none border-2 border-gray-500 bg-white checked:bg-transparent checked:border-0 svelte-egpy0w</value>
      <webElementGuid>ed38e050-c974-495f-9f52-fde2347126bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[2]/div[@class=&quot;flex&quot;]/div[@class=&quot;pb-6 w-full bg-[#e8efee] min-h-screen lg:pl-[246px] main-container-transition-open svelte-og1l5i&quot;]/div[@class=&quot;px-2 pt-2 w-full mx-auto&quot;]/div[@class=&quot;w-full bg-white rounded shadow-[0px_1px_3px_0px_rgb(54,74,99,0.05)] p-4 space-y-4&quot;]/div[3]/div[@class=&quot;w-full overflow-x-auto&quot;]/table[@class=&quot;responsive-table&quot;]/tbody[@class=&quot;text-sm&quot;]/tr[2]/td[@class=&quot;pl-5&quot;]/div[1]/div[@class=&quot;bg-gray-200 rounded-sm w-5 h-5 flex flex-shrink-0 justify-center items-center relative&quot;]/input[@class=&quot;input-check focus:opacity-100 checkbox absolute cursor-pointer w-full h-full appearance-none border-2 border-gray-500 bg-white checked:bg-transparent checked:border-0 svelte-egpy0w&quot;]</value>
      <webElementGuid>b9f782b4-45e4-47d7-9e98-2f893fd28e03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='60']</value>
      <webElementGuid>81ecc7c9-4a1e-4589-8536-600dbf449ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/input</value>
      <webElementGuid>bd841864-34ab-4644-87dc-ed91318d519a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'checkbox' and @type = 'checkbox']</value>
      <webElementGuid>9e694623-f4fc-4d97-bb8f-301a53187e51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
