<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputtoken</name>
   <tag></tag>
   <elementGuidId>fdb15df7-3b96-4156-80e8-d88e64879aa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#token</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='token']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f1efb8c-bce8-481e-b55c-21dbf74c85e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>token</value>
      <webElementGuid>b8ffddb8-0427-40e6-95f2-6c4212210c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>38cd2208-a43f-4097-8d43-7ce5482298a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>b139e800-0bad-4b22-9afb-ab95ca778928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tokenHelp</value>
      <webElementGuid>a63e0438-8d06-44b7-b1ea-7af04fb664e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>token</value>
      <webElementGuid>776be14a-bbd4-4c85-a38d-a9faefbf9990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>aea18866-2772-49a8-8fd9-2cf7a9984aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;token&quot;)</value>
      <webElementGuid>dbd6ec92-adf3-4e84-ade5-08d398441bfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='token']</value>
      <webElementGuid>1a748406-5450-47cb-b8c4-b15bda1b141b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>16f927f5-46bb-47da-8acc-8e37012f294e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'token' and @type = 'text' and @placeholder = 'Email']</value>
      <webElementGuid>eafe4ae5-9d11-441c-b4b9-2d6180a6bd71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
