<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih KelasX - A Jenjang 10, Total M_8ab355</name>
   <tag></tag>
   <elementGuidId>2d801661-3587-4a1f-bcc4-1645fb6a05dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grid-state</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='grid-state']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>88063846-f791-459c-9bb8-1bd3a9393da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500</value>
      <webElementGuid>76dc4d90-d1ad-40ea-b1eb-0689ad902eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grid-state</value>
      <webElementGuid>3c0f8229-c726-4101-b276-41f10f0bd70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih KelasX - A [Jenjang: 10, Total Murid: 2]X - B [Jenjang: 10, Total Murid: 1]X - C [Jenjang: 12, Total Murid: 1]XII MIPA 2 [Jenjang: 12, Total Murid: 0]</value>
      <webElementGuid>e1e8dfda-d393-4e92-b9be-f240ff0dfca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[2]/div[@class=&quot;flex&quot;]/div[@class=&quot;pb-6 w-full bg-[#e8efee] min-h-screen lg:pl-[246px] main-container-transition-open svelte-og1l5i&quot;]/div[@class=&quot;px-2 pt-2 w-full mx-auto&quot;]/div[@class=&quot;bg-white rounded shadow-[0px_1px_3px_0px_rgb(54,74,99,0.05)] p-4 space-y-4&quot;]/div[@class=&quot;grid mt-2 gap-5 grid-rows-2 md:grid-rows-none md:grid-cols-2&quot;]/div[@class=&quot;space-y-4 mb-4&quot;]/div[2]/div[@class=&quot;flex flex-col space-y-6&quot;]/div[@class=&quot;space-y-1&quot;]/div[@class=&quot;relative&quot;]/select[@id=&quot;grid-state&quot;]</value>
      <webElementGuid>3ad9b888-e619-42f1-9d88-8d358935197c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='grid-state']</value>
      <webElementGuid>0389d444-03c9-450b-a62c-ad953f5fb2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4c007e5e-6135-49a5-a458-e3cd78e8cecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'grid-state' and (text() = 'Pilih KelasX - A [Jenjang: 10, Total Murid: 2]X - B [Jenjang: 10, Total Murid: 1]X - C [Jenjang: 12, Total Murid: 1]XII MIPA 2 [Jenjang: 12, Total Murid: 0]' or . = 'Pilih KelasX - A [Jenjang: 10, Total Murid: 2]X - B [Jenjang: 10, Total Murid: 1]X - C [Jenjang: 12, Total Murid: 1]XII MIPA 2 [Jenjang: 12, Total Murid: 0]')]</value>
      <webElementGuid>1f833c5f-7d50-49f9-88fa-23018662b874</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
