<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kelas</name>
   <tag></tag>
   <elementGuidId>24e12b98-c39d-49ac-84e9-e57b1da77406</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[text()='Kelas']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>72dbdc8e-a945-4540-b0fa-2bdb9d503c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/kelas</value>
      <webElementGuid>df3c713a-6551-49f8-8903-c89f3de4d7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white hover:text-amber-500 flex items-center p-2 pl-11 w-full rounded-lg transition duration-75 group text-sm</value>
      <webElementGuid>f4419be5-74bc-4932-abcf-98b17702c816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kelas</value>
      <webElementGuid>da969385-95b3-4491-80ea-16c3974e2d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left-navigation&quot;)/div[@class=&quot;px-4 h-full scroll mt-8 svelte-og1l5i&quot;]/div[2]/ul[@class=&quot;space-y-2 tracking-wide mt-8 transition duration-500&quot;]/li[@class=&quot;whitespace-nowrap&quot;]/ul[@class=&quot;py-2 space-y-2 dropdown-elm&quot;]/li[1]/a[@class=&quot;text-white hover:text-amber-500 flex items-center p-2 pl-11 w-full rounded-lg transition duration-75 group text-sm&quot;]</value>
      <webElementGuid>bf71a69b-a2c0-4025-af6d-5188232ef340</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='left-navigation']/div/div[2]/ul/li[4]/ul/li/a</value>
      <webElementGuid>58572410-25d0-492c-9b8a-22859d7abf32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kelas')]</value>
      <webElementGuid>2014facc-f79b-4bce-ad9c-9bb3501a9c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/kelas')]</value>
      <webElementGuid>7fb6df9d-6aec-4ec0-a99a-fb4c3ea8d798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li/a</value>
      <webElementGuid>cc921f21-659f-4e68-98b0-f8bf880b8e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/kelas' and (text() = 'Kelas' or . = 'Kelas')]</value>
      <webElementGuid>3b3b6832-d185-49d3-81c9-7f988541a397</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
