<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_1 Jam</name>
   <tag></tag>
   <elementGuidId>2132e4fa-11a6-4ac7-b1c3-eae74b738b84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b-fasttime']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b-fasttime</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d4983b54-03c3-4536-96da-281c0aa7bb67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b-fasttime</value>
      <webElementGuid>f28700f2-e3bc-468f-8589-feeb6043bd9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border border-teal-100 py-2 text-teal-100 rounded-sm</value>
      <webElementGuid>a38ac859-71a5-4634-9b3c-ce1dbc7c6c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 Jam</value>
      <webElementGuid>62334194-2492-4df2-abd5-2d5e0c94d5e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[2]/div[@class=&quot;flex&quot;]/div[@class=&quot;pb-6 w-full bg-[#e8efee] min-h-screen lg:pl-[246px] main-container-transition-open svelte-og1l5i&quot;]/div[@class=&quot;px-2 pt-2 w-full mx-auto&quot;]/div[@class=&quot;bg-white rounded shadow-[0px_1px_3px_0px_rgb(54,74,99,0.05)] p-4 space-y-4&quot;]/div[@class=&quot;grid mt-2 gap-5 grid-rows-2 md:grid-rows-none md:grid-cols-2&quot;]/div[@class=&quot;space-y-4 mb-4&quot;]/div[@class=&quot;bg-teal-700 p-2 rounded-md space-y-4&quot;]/div[@class=&quot;grid gap-3 grid-cols-2 sm:grid-cols-4&quot;]/button[@id=&quot;b-fasttime&quot;]</value>
      <webElementGuid>84034930-51d8-4739-b39b-4f8d9fe1b206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b-fasttime']</value>
      <webElementGuid>e3b994ca-4722-49b0-ac39-023304bbbe41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>8786d145-d459-41b3-a971-94077428e13f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'b-fasttime' and (text() = '1 Jam' or . = '1 Jam')]</value>
      <webElementGuid>76248aad-d78d-40f9-8067-7f63ba69e936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
