<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih Mata PelajaranFAK - 1 Fisika X_752ace</name>
   <tag></tag>
   <elementGuidId>a8616633-046f-4da0-b2eb-b6b6fc151f54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='grid-state'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.grid.grid-cols-2.gap-4.border-solid.border-2.border-green-500.p-3.rounded > div.space-y-1 > div.relative > #grid-state</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6c31cf47-6ed4-4037-b0e2-39f646ab28a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500</value>
      <webElementGuid>cb3d1633-8acd-4a18-901e-40f6436fae8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grid-state</value>
      <webElementGuid>a1e76986-1f76-4113-93fa-3a99cfdaaf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih Mata Pelajaran[FAK - 1] Fisika X[FAK - 2 - 2] Fisika XI[BAHASA - 4 - 4] Bahasa[UMUM - 5] Pengetahuan Umum[BAHASA - 6] Bahasa Inggris[AGAMA - 11] PAI</value>
      <webElementGuid>4839b790-91b7-4af4-9865-47fe0d3fddd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[2]/div[@class=&quot;flex&quot;]/div[@class=&quot;pb-6 w-full bg-[#e8efee] min-h-screen lg:pl-[246px] main-container-transition-open svelte-og1l5i&quot;]/div[@class=&quot;px-2 pt-2 w-full mx-auto&quot;]/div[@class=&quot;bg-white rounded shadow-[0px_1px_3px_0px_rgb(54,74,99,0.05)] p-4 space-y-4&quot;]/div[@class=&quot;grid mt-2 gap-5 grid-rows-2 md:grid-rows-none md:grid-cols-2&quot;]/div[@class=&quot;space-y-4 mb-4&quot;]/div[3]/div[@class=&quot;flex flex-col space-y-6&quot;]/div[@class=&quot;grid grid-cols-2 gap-4 border-solid border-2 border-green-500 p-3 rounded&quot;]/div[@class=&quot;space-y-1&quot;]/div[@class=&quot;relative&quot;]/select[@id=&quot;grid-state&quot;]</value>
      <webElementGuid>20f9c668-2394-4a15-b4e1-b903f26c4152</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='grid-state'])[3]</value>
      <webElementGuid>066e5407-8eaf-47a2-89a6-756bc3efc703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/select</value>
      <webElementGuid>435fe6a6-280d-4d24-bc1c-a7a4305f13d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'grid-state' and (text() = 'Pilih Mata Pelajaran[FAK - 1] Fisika X[FAK - 2 - 2] Fisika XI[BAHASA - 4 - 4] Bahasa[UMUM - 5] Pengetahuan Umum[BAHASA - 6] Bahasa Inggris[AGAMA - 11] PAI' or . = 'Pilih Mata Pelajaran[FAK - 1] Fisika X[FAK - 2 - 2] Fisika XI[BAHASA - 4 - 4] Bahasa[UMUM - 5] Pengetahuan Umum[BAHASA - 6] Bahasa Inggris[AGAMA - 11] PAI')]</value>
      <webElementGuid>a781d8bc-96b6-4dc0-b130-c6bcbbe16cea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
