<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih KelasX - A Jenjang 10, Total M_8ab355</name>
   <tag></tag>
   <elementGuidId>6d447968-17f5-4629-a0c3-98e12e2465ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='grid-state']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#grid-state</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0fe44f9a-2216-4ef0-84c1-0f1e77d01b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500</value>
      <webElementGuid>cf5f6503-074c-4056-853c-662bafc01ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grid-state</value>
      <webElementGuid>5673aaaf-be80-4b54-a4f8-af0d5dd0f474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih KelasX - A [Jenjang: 10, Total Murid: 2]X - B [Jenjang: 10, Total Murid: 1]X - C [Jenjang: 12, Total Murid: 1]XII MIPA 2 [Jenjang: 12, Total Murid: 0]</value>
      <webElementGuid>14778988-dec2-4e74-9745-2dc773c089ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[2]/div[@class=&quot;flex&quot;]/div[@class=&quot;pb-6 w-full bg-[#e8efee] min-h-screen lg:pl-[246px] main-container-transition-open svelte-og1l5i&quot;]/div[@class=&quot;px-2 pt-2 w-full mx-auto&quot;]/div[@class=&quot;bg-white rounded shadow-[0px_1px_3px_0px_rgb(54,74,99,0.05)] p-4 space-y-4&quot;]/div[@class=&quot;grid mt-2 gap-5 grid-rows-2 md:grid-rows-none md:grid-cols-2&quot;]/div[@class=&quot;space-y-4 mb-4&quot;]/div[3]/div[@class=&quot;flex flex-col space-y-6&quot;]/div[@class=&quot;space-y-1&quot;]/div[@class=&quot;relative&quot;]/select[@id=&quot;grid-state&quot;]</value>
      <webElementGuid>abced717-ae0e-498a-9ab6-8f8cb399b6c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='grid-state']</value>
      <webElementGuid>4617a56d-c4d6-425b-9db6-dd23620cb8ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>2aabd47b-2763-40fc-ae98-309535279eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'grid-state' and (text() = 'Pilih KelasX - A [Jenjang: 10, Total Murid: 2]X - B [Jenjang: 10, Total Murid: 1]X - C [Jenjang: 12, Total Murid: 1]XII MIPA 2 [Jenjang: 12, Total Murid: 0]' or . = 'Pilih KelasX - A [Jenjang: 10, Total Murid: 2]X - B [Jenjang: 10, Total Murid: 1]X - C [Jenjang: 12, Total Murid: 1]XII MIPA 2 [Jenjang: 12, Total Murid: 0]')]</value>
      <webElementGuid>9027e0f8-31c3-45b5-895e-5cf3e03fe3be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
