<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox</name>
   <tag></tag>
   <elementGuidId>9779aa60-870a-4f06-abcc-9e3e0a2f6a53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='4']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9adcea07-d58c-4062-a332-474fe539a1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d5154062-8f13-4500-92d1-4d5e9a3c87ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d585675d-0d4b-4c9f-ae34-7944ee7c2148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>71</value>
      <webElementGuid>a661f064-ab71-4ac0-a55d-3aa13361317c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-check focus:opacity-100 checkbox absolute cursor-pointer w-full h-full appearance-none border-2 border-gray-500 bg-white checked:bg-transparent checked:border-0 svelte-181mww0</value>
      <webElementGuid>77806be7-d9ae-4a54-87e6-ea3647841963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[2]/div[@class=&quot;flex&quot;]/div[@class=&quot;pb-6 w-full bg-[#e8efee] min-h-screen lg:pl-[246px] main-container-transition-open svelte-og1l5i&quot;]/div[@class=&quot;px-2 pt-2 w-full mx-auto&quot;]/div[@class=&quot;p-4 bg-white rounded shadow-[0px_1px_3px_0px_rgb(54,74,99,0.05)] space-y-4&quot;]/div[@class=&quot;mt-4 overflow-x-auto&quot;]/table[@class=&quot;w-full whitespace-nowrap&quot;]/tbody[1]/tr[@class=&quot;even:bg-gray-100 h-[60px]&quot;]/td[1]/div[@class=&quot;ml-5&quot;]/div[@class=&quot;bg-gray-200 rounded-sm w-5 h-5 flex flex-shrink-0 justify-center items-center relative&quot;]/input[@class=&quot;input-check focus:opacity-100 checkbox absolute cursor-pointer w-full h-full appearance-none border-2 border-gray-500 bg-white checked:bg-transparent checked:border-0 svelte-181mww0&quot;]</value>
      <webElementGuid>d9e1c45f-acfc-4226-baf4-c3f58b26e00b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='71']</value>
      <webElementGuid>4b9cfede-64e8-4b5d-8986-90d1f6b45730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/input</value>
      <webElementGuid>cfce68c7-ac8e-4233-aee5-5769ade12760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'checkbox' and @type = 'checkbox']</value>
      <webElementGuid>5faae8cc-b603-4128-a18d-c7362406ab16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
