<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buat Ujian</name>
   <tag></tag>
   <elementGuidId>7e56acd7-a8aa-44d5-84be-95b9b60bb698</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='left-navigation']/div/div[2]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.bg-amber-300.px-4.py-3.flex.items-center.rounded.justify-between.w-full</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed62332e-6e8b-4aae-aceb-bb1b82b50afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/create-ujian</value>
      <webElementGuid>e2c70bb1-01ba-4c75-b5e8-830f4cf57ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>dashboard</value>
      <webElementGuid>63c9a8cf-a4f1-43ed-b783-76fcb571c391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-amber-300 px-4 py-3 flex items-center rounded justify-between w-full</value>
      <webElementGuid>3706e1b9-d0da-456a-b2bd-98e8fd230cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buat Ujian </value>
      <webElementGuid>32afd2d9-e8a6-49c5-b02c-7617ee52e6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;left-navigation&quot;)/div[@class=&quot;px-4 h-full scroll mt-8 svelte-og1l5i&quot;]/div[2]/ul[@class=&quot;space-y-2 tracking-wide mt-8 transition duration-500&quot;]/li[@class=&quot;mb-5 whitespace-nowrap&quot;]/a[@class=&quot;bg-amber-300 px-4 py-3 flex items-center rounded justify-between w-full&quot;]</value>
      <webElementGuid>5051d141-cf08-4864-bc46-a752fa2ae257</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='left-navigation']/div/div[2]/ul/li/a</value>
      <webElementGuid>c2717265-cb6a-42d5-b5f3-b117cc409b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/create-ujian')]</value>
      <webElementGuid>d9659c8f-65f1-4c21-af89-be9b7fb796c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>f85564ad-cd6f-4e79-bbd1-f5352efd63ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/create-ujian' and (text() = 'Buat Ujian ' or . = 'Buat Ujian ')]</value>
      <webElementGuid>e3c5d615-6a3c-438f-9068-685aa95e6a15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
