<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih KelasX - A Jenjang 10, Total M_7e76ba</name>
   <tag></tag>
   <elementGuidId>d0e3f452-6d3e-4ede-8eda-0fc9d784c66c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='grid-state']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#grid-state</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>887702d9-96ca-4245-920a-dd27c36fbb18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500</value>
      <webElementGuid>6b47c1d6-3e2b-462b-ad90-b8224a382440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grid-state</value>
      <webElementGuid>34214e05-4fea-47b8-825a-f82a04efb815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih KelasX - A [Jenjang: 10, Total Murid: 2]X - B [Jenjang: 10, Total Murid: 2]X - C [Jenjang: 12, Total Murid: 2]X - D [Jenjang: 10, Total Murid: 4]XI IPA - 2 [Jenjang: 11, Total Murid: 2]</value>
      <webElementGuid>9fe7514c-39bb-41ad-a36c-890437722bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[2]/div[@class=&quot;flex&quot;]/div[@class=&quot;pb-6 w-full bg-[#e8efee] min-h-screen lg:pl-[246px] main-container-transition-open svelte-og1l5i&quot;]/div[@class=&quot;px-2 pt-2 w-full mx-auto&quot;]/div[@class=&quot;bg-white rounded shadow-[0px_1px_3px_0px_rgb(54,74,99,0.05)] p-4 space-y-4&quot;]/div[@class=&quot;grid mt-2 gap-5 grid-rows-2 md:grid-rows-none md:grid-cols-2&quot;]/div[@class=&quot;space-y-4 mb-4&quot;]/div[2]/div[@class=&quot;flex flex-col space-y-6&quot;]/div[@class=&quot;space-y-1&quot;]/div[@class=&quot;relative&quot;]/select[@id=&quot;grid-state&quot;]</value>
      <webElementGuid>935e4dcb-1b2f-410f-b76d-e9ef3014d8a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='grid-state']</value>
      <webElementGuid>d9b1ab6e-43fb-4507-996d-f68a3f04de57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>5126b47d-f57f-485c-a813-8a481dee10f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'grid-state' and (text() = 'Pilih KelasX - A [Jenjang: 10, Total Murid: 2]X - B [Jenjang: 10, Total Murid: 2]X - C [Jenjang: 12, Total Murid: 2]X - D [Jenjang: 10, Total Murid: 4]XI IPA - 2 [Jenjang: 11, Total Murid: 2]' or . = 'Pilih KelasX - A [Jenjang: 10, Total Murid: 2]X - B [Jenjang: 10, Total Murid: 2]X - C [Jenjang: 12, Total Murid: 2]X - D [Jenjang: 10, Total Murid: 4]XI IPA - 2 [Jenjang: 11, Total Murid: 2]')]</value>
      <webElementGuid>293b5bd0-f319-4f91-bd4a-bfc07109b247</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
