<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_dropbtn</name>
   <tag></tag>
   <elementGuidId>5ae33630-8495-44a8-82a9-65a2ef6e76ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='w-full overflow-x-auto']/table[@class='responsive-table']/tbody/tr[1]/td[9]/div/button/svg</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.dropbtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>0d79eeac-b750-4cbe-adf4-f44485f9d7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropbtn</value>
      <webElementGuid>7a548507-3631-4a7f-94fa-505a25caaf22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>4d3f2253-2f4f-4591-a67d-b991346fd523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>c4ecb0da-077e-4fa0-964a-9a1f27d13f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>93298090-7bec-4dca-87d3-f0d38e670dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 20 20</value>
      <webElementGuid>e3eeb7c3-c359-4c24-8645-66c1fb65c35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>2b38873b-30d4-417c-b447-e4123456e7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[2]/div[@class=&quot;flex&quot;]/div[@class=&quot;pb-6 w-full bg-[#e8efee] min-h-screen lg:pl-[246px] main-container-transition-open svelte-og1l5i&quot;]/div[@class=&quot;px-2 pt-2 w-full mx-auto&quot;]/div[@class=&quot;w-full bg-white rounded shadow-[0px_1px_3px_0px_rgb(54,74,99,0.05)] p-4 space-y-4&quot;]/div[3]/div[@class=&quot;w-full overflow-x-auto&quot;]/table[@class=&quot;responsive-table&quot;]/tbody[@class=&quot;text-sm&quot;]/tr[1]/td[9]/div[@class=&quot;sm:px-5 relative flex items-center gap-6&quot;]/button[@class=&quot;focus:ring-2 rounded-md focus:outline-none border-2&quot;]/svg[@class=&quot;dropbtn&quot;]</value>
      <webElementGuid>dafbcd9e-1ae1-4733-86a0-8266bb06c5a2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
